export enum TransactionTypesEnum {
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  REFERRAL_PAYMENT = 'REFERRAL_PAYMENT',
  TRADING_BOT_PURCHASE = 'TRADING_BOT_PURCHASE',
  TRADING_BOT_TOP_UP = 'TRADING_BOT_TOP_UP',
  WITHDRAW_PROFIT = 'WITHDRAW_PROFIT',
  TRADING_BOT_ON_COMPLETE = 'TRADING_BOT_ON_COMPLETE',
  REFERRAL_DISTRIBUTION = 'REFERRAL_DISTRIBUTION',
  REFERRAL_NEW_LEVEL_PREMIUM = 'REFERRAL_NEW_LEVEL_PREMIUM',
  TRADING_BOT_WITHDRAW_PROFIT = 'TRADING_BOT_WITHDRAW_PROFIT',
  TRADING_BOT_CLOSED = 'TRADING_BOT_CLOSED',
}
