export enum ExceptionsEnum {
  NOT_VALID_IP_ADDRESS = '2-e-fe',
  NEED_AGREE_WITH_TERMS_AND_CONDITIONS = '3-e-fe',
  PASSWORDS_MISMATCH = '4-e-fe',
  MIN_LENGTH_IS = '5-e-fe',
  MAX_LENGTH_IS = '6-e-fe',
  WRONG_PASSWORD_FORMAT = '7-e-fe',
  NOT_VALID_EMAIL = '8-e-fe',
  FIELD_IS_REQUIRED = '9-e-fe',
  MIN_VALUE_IS = '10-e-fe',
  MAX_VALUE_IS = '11-e-fe',
  VALUE_MUST_BE_MORE_THAN = '20-e-fe',
  WRONG_TRX_ADDRESS = '21-e-fe',
  WRONG_BTC_ADDRESS = '22-e-fe',
  WRONG_EVM_ADDRESS = '23-e-fe',
  NOT_ENOUGH_FUNDS = '24-e-fe',
  SAME_VALUES = '26-e-fe',
  MAX_NUMBER_OF_DECIMAL_PLACES = '29-e-fe',
  VALUE_MUST_BE_LESS_THAN = '30-e-fe',
}
